### ISSUE TITLE
existing reproducible workflow should reference this repo

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-ost/ghactions4r#1]
Instead of nmfs-stock-synthesis/workflows

- [x] r4ss
- [x] ss3sim
- [x] SSMSE
- [ ] r4mas? (or other that @Bai-Li-NOAA has used

**Comment by Bai-Li-NOAA** [comment]
- [x] nmfspalette (@ChristineStawitz-NOAA's nmfspalette is a nice package to be used for testing, Bai forked it and will work on it before testing r4mas)

**Comment by k-doering-NOAA** [comment]
Sounds good @Bai-Li-NOAA . Feel free to close this issue if you don't need it (the workflows I use are now referencing this ghactions4r repo)

**Comment by Bai-Li-NOAA** [comment]
Great. I am working on it this week. Will close the issue after completing the tasks.

**Comment by Bai-Li-NOAA** [comment]
r4mas still has some issues that need to be resolved before doing any workflow testing and I am not sure about the timeline. So I will close this issue without making any modifications in r4mas, but I will continue testing new workflows from the ghactions4r using nmfspalette.
