### ISSUE TITLE
options for r-cmd-check.yml

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-ost/ghactions4r#11]
For both SSMSE and r4ss, the 'oldrel-2' config is currently failing (this is R 3.6.x, I think, currently). For SSMSE, we decided it wasn't worth debugging (seems to be due to issues with loading pkg dependencies) and just change the minimum version of R to 4.0.5. However, the job still fails, and it would be nice to remove it.

I wonder if we should have a few different matrix options for r-cmd-check? Maybe one that does just the current version of R with all 3 OSes, and one that does the older checks as well? I'm open to other thoughts as to what those options would be.

@Bai-Li-NOAA thoughts?

**Comment by Bai-Li-NOAA** [comment]
Maybe we could create two workflows (r-cmd-check-standard.yml and r-cmd-check-full.yml) and add a parameter (e.g. use_full_build_matrix=FALSE or TRUE) in the use_r_cmd_check function? 

The r-cmd-check-standard.yml could be the default one and works on current version of R with all 3 OSes. The r-cmd-check-full.yml works when use_full_build_matrix=TRUE and works on older versions of R and devel R.

**Comment by k-doering-NOAA** [comment]
Thanks, Bai!

I was thinking along these lines, except just using an input parameter for use_full_build_matrix in the workflow, so that we only need one workflow? I think we could use an if statement to set up the two alternative build matrices. The nice thing about this is also exiting workflows would not need to change their references (we could make use_full_build_matrix  = false the default).  I can work on setting this up and submit it as a PR for you to check, if that sounds like the way to go

I like the idea of making the "standard" being default.

**Comment by Bai-Li-NOAA** [comment]
Using if statement in one workflow sounds better! Happy to review the PR.

**Comment by k-doering-NOAA** [comment]
Sounds good! I'll get started on the PR and tag you as a reviewer when it is done

**Comment by Bai-Li-NOAA** [comment]
I tested the R code and generated two workflows for nmfspalette. Both [standard R CMD check](https://github.com/nmfs-fish-tools/nmfspalette/actions/runs/1773382871) and [full R CMD check](https://github.com/nmfs-fish-tools/nmfspalette/actions/runs/1773382873) worked fine. Thanks for updating the R function. 👍

**Comment by k-doering-NOAA** [comment]
Thanks @Bai-Li-NOAA !
