### ISSUE TITLE
[Feature]: add `use-public-rspm` option to calc-coverage workflow

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-ost/ghactions4r#110]
### Is your feature request related to a problem? Please describe.

@Andrea-Havron-NOAA noted that the calc coverage workflow also needs the latest version of matrix for tmb packages (see #106 )

### Describe the solution you would like.

Add a new option to calc-coverage workflow

### Describe alternatives you have considered

n/a

**Comment by k-doering-NOAA** [comment]
@Andrea-Havron-NOAA I started to work on this, and then was reminded that the calc-coverage workflow runs on ubuntu, so shouldn't be affected by the matrix/tmb issue.

Do you think the failure could be related to a different issue?

**Comment by Andrea-Havron-NOAA** [comment]
In my clustTMB package, both the [calc-coverage](https://github.com/Andrea-Havron/clustTMB/actions/runs/7588377619/job/20670749612#step:4:6805) and [r-cmd-check](https://github.com/Andrea-Havron/clustTMB/actions/runs/7588377623/job/20670756107#step:5:7741) workflows are installing the older Matrix package (v 1.6-1.1) and the newer TMB package (v 1.9.10). The [calc-coverage](https://github.com/Andrea-Havron/clustTMB/actions/runs/7588377619/job/20670749612#step:5:29) workflow throws a warning on the version conflict while the [r-cmd-check](https://github.com/Andrea-Havron/clustTMB/actions/runs/7588377623/job/20670756107#step:7:44) workflow does not. Are the package installation steps different and would this affect the versioning conflict? I don't see output from the clustTMB compilation step in the r-cmd-check workflow while I can see it in the calc-coverage workflow.

**Comment by k-doering-NOAA** [comment]
I think this is the difference in the calc-coverage workflow:

https://github.com/nmfs-fish-tools/ghactions4r/blob/16d88a2fb65b756bdd149c5d79f32acde763f46c/.github/workflows/calc-coverage.yml#L18

It means that compiled packages are coming from the [posit package manager](https://packagemanager.posit.co/client/#/), which is normally great so you don't have to compile from source for every linux package.

I just tested and turning off rspm seems to make calc-cov work for clustTMB, but the run takes longer. I'm thinking to add an option 
`use-public-rspm` that defaults to true that can be added to the github action workflow.
