### ISSUE TITLE
scope out features of ghactions4r

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-ost/ghactions4r#12]
I recently learned that there is a function `usethis::use_pkgdown_github_pages()` which does everything you need (I think) to set up pkgdown to build from gh-pages branch.

I wonder if the ghactions4r function should do something similar, rather than just put the package down yml workflow in the right place? I could see value in this, although I think the usethis::use_pkgdown_github_pages() might go a little too far (it changes settings in github, including creating the gh-pages branch and changing the github pages rendering source to be the gh-pages branch. We could also have different options, depending on what folks want (i.e., just add the automated workflow, or take care of some other details as well.)

**Comment by Bai-Li-NOAA** [comment]
I wonder if a GitHub poll would help gather user feedback (e.g. sending the poll to NMFS R-User Space). The steps include: 
- install GitHub poll for the repo: [https://github.com/apps/polls](https://github.com/apps/polls)
- create poll options here: [https://app.gh-polls.com/](https://app.gh-polls.com/)
- copy markdown text to this issue page

**Comment by k-doering-NOAA** [comment]
That's a great idea, @Bai-Li-NOAA - I think that is a great way to get more broad feedback, too. 

Perhaps we can put  something together to share at the Feb 15 nmfs r users group meeting? (The Feb 1 one seems a little too soon to me).

**Comment by Bai-Li-NOAA** [comment]
Feb 15 sounds good. I created a poll for testing here: [https://github.com/Bai-Li-NOAA/ghtest/issues/1](https://github.com/Bai-Li-NOAA/ghtest/issues/1). Below are some limitations of the poll:

- You can vote multiple times with different IPs, so it would be good to write some simple do's and don'ts.
- The poll tracks votes forever. It might be good to specify a deadline for voting.
- I do not know how to check the stored voting data in DynamoDB and only know how to check the individual markdown SVG images in the issue.

**Comment by k-doering-NOAA** [comment]
we could also just do a google forms poll, if that seems easier! I've never used this polling tool, either, but I think if you think it has some improved features over a google forms poll, then it seems worth investigating.

**Comment by k-doering-NOAA** [comment]
It is cool that you can just click on the options near the bar graph to vote! I honestly didn't understand how it worked at first though, and accidentally "voted" a few times 😂 (I thought clicking on the bar would take me to a page to vote...oops). Seems like it would work fine with a message like "click on the bar of your choice to vote".

**Comment by Bai-Li-NOAA** [comment]
Agree, it would be good to add an instruction message if the GitHub poll app is used. I like the poll app more than Google forms because you can vote and visualize the results in the same issue page. An alternative solution may be to describe individual options using comments and invite people to vote using the thumbs up emoji (getting inspiration from your last comment 😄 ). It is easy to be implemented and easy to count votes. See example here: [https://github.com/Bai-Li-NOAA/ghtest/issues/1](https://github.com/Bai-Li-NOAA/ghtest/issues/1)

**Comment by k-doering-NOAA** [comment]
I like this second idea! Lower tech, but honestly I think this is a lot clearer.

**Comment by k-doering-NOAA** [comment]
Oops, somehow the Feb 15 meeting slipped my radar (I had it on my calendar, but read the event wrong and didn't realize it was an R users group meeting!

Still would be great to do a poll at a later meeting.

**Comment by k-doering-NOAA** [comment]
@Bai-Li-NOAA , what do you think about using github discussions in the ghactions4r repo as a way to do the poll? I can contact Emily and see if she could give us a bit of time (5 min or less) to plug the poll in the next meeting. 

Here's what I would like to know from folks - @Bai-Li-NOAA , could you edit or add to this when you have time? Once we figure it out, I can then open these as discussions.

## Which github actions would you like to use for R?
 - run r-cmd-check for an r package
 -  build and deploy bookdown automatically
 - build r markdown automatically
 - build and deploy package down sites
 - automatically style r code
 - automatically update documentation (devtools::document)
 -  Other (please comment with ideas!)
 
## How much help with setup would you want for actions that work with github pages?
1. A function initializes the files I need to run the github action
 2. A function creates needed branches and sets up github pages in addition to creating files, if necessary.

**Comment by k-doering-NOAA** [comment]
Note added to general announcements for the March 8 Meeting, which is the next one I see on the calendar. https://docs.google.com/document/d/1mrgtrSXVtPCTxrpBa_0ZbxEsnK9vcQzs6RIV3f-OTPw/edit#heading=h.nph2bbb4mocw

I can plan on attending and making the quick plug.

**Comment by Bai-Li-NOAA** [comment]
Posting the options on the discussion page is great. You covered everything and I have no edits/suggestions. I can help testing the "vote" function on the discussion page.

I can add other suggestions to the discussion page:

- Add a Gitleak Action to run gitleaks in your CI/CD pipeline for finding secrets in git repositories (e.g., passworks, API keys, and tokens)

Thanks for adding the notes to the R UG meeting. I will attend that one too!

**Comment by k-doering-NOAA** [comment]
I like the gitleak action idea, definitely a great idea to add to the list.

I will work on putting these ideas into discussions soon.

**Comment by k-doering-NOAA** [comment]
@Bai-Li-NOAA I added the two question in the discussions: https://github.com/nmfs-fish-tools/ghactions4r/discussions/16 and https://github.com/nmfs-fish-tools/ghactions4r/discussions/17. Feel free to edit or add to! I realize the "upvote" button might be the easiest way for folks to vote.

**Comment by Bai-Li-NOAA** [comment]
Just tested it out. The discussion pages look really nice! Do you think there is a need to set up a deadline for each discussion question? For example, the developers will start the first round of development by using the feedback that is submitted before March 31. Or maybe just mention that the developers would check the discussion pages at the end of each month to adjust the development focuses?

**Comment by k-doering-NOAA** [comment]
Hmm, good point! I like the idea of just saying we will incorporate feedback we get by March 31.

**Comment by k-doering-NOAA** [comment]
Here is what I am seeing on the discussions as of today  - numbers in parentheses are the number of upvotes

## Which github actions would you like to use for R?
 - run r-cmd-check for an r package (4)
 -  build and deploy bookdown automatically (3)
 - build r markdown automatically ( was accidentally not included as an option)
 - build and deploy package down sites (3)
 - automatically style r code (3)
 - automatically update documentation (devtools::document) (3)
 -  Git leaks (2)
 
## How much help with setup would you want for actions that work with github pages?
1. A function initializes the files I need to run the github action (2)
 2. A function creates needed branches and sets up github pages in addition to creating files, if necessary. (2)

I guess my takeaways from this poll are that all of the workflows we have considered are useful to at least a subset of users! And while some would like the function to do everything, others would rather it not. I'm guessing this depends on the level of comfort with github?

**Comment by k-doering-NOAA** [comment]
closing, as I have opened issues for new features. Users are always welcome to submit new ideas through the ghactions4r issues!
