### ISSUE TITLE
[Bug]: Deprecate doc, style, and style description stand alone workflows

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-ost/ghactions4r#126]
### Describe the bug

I'm working on this package related to ageing error and just added a bunch of workflows thanks to {ghactions4r}: https://github.com/pfmc-assessments/AgeingError/actions.

At first I ran all three of 
`ghactions4r::use_update_roxygen_docs()`,
`ghactions4r::use_style_r_code()`, and 
`ghactions4r::use_style_description()`

But the `call-style` action is failing with messages related to missing roxygen2 or knitr: https://github.com/pfmc-assessments/AgeingError/actions/runs/9308136774/job/25620898566#step:5:43.

However, the action added via 
`ghactions4r::use_doc_and_style_r()`
was able to successfully style the code, suggesting that it's an issue with the workflow, not the code being styled.

Maybe adding a section of `extra-packages` like https://github.com/nmfs-fish-tools/ghactions4r/blob/main/.github/workflows/doc-and-style-r.yml#L61-L69 to the style-r-code workflow would get it working?

It might also be worth re-ordering the README to put `ghactions4r::use_doc_and_style_r()` above the three functions which are essentially subsets of the first. In general I would guess that it's nicer to use the combined workflow.

### To Reproduce

Look at failed action linked above.

### Expected behavior

Action passing via successful styling of code and creating pull request

**Comment by k-doering-NOAA** [comment]
great points @iantaylor-NOAA! This also makes me wonder if we should deprecate `ghactions4r::use_update_roxygen_docs()`,`ghactions4r::use_style_r_code()`, and `ghactions4r::use_style_description()` because they are not used as often, and therefore more likely to have issues that go unnoticed for too long.

**Comment by iantaylor-NOAA** [comment]
@k-doering-NOAA, good idea to just deprecate those functions. I think that would have multiple benefits to maintaining this package. Folks could just copy the yml files from the git history rather than rely on if they really want to keep using that specific action rather than rely on ghactions4r.

If you're deprecating the "use_*" functions, I'm guessing you would also deprecate the workflows that they call on.

The public repos which use each of the three actions are pretty small in number and mostly folks that we know so could proactively move away from using these actions without even hitting the deprecation message.
https://github.com/search?q=nmfs-fish-tools%2Fghactions4r%2F.github%2Fworkflows%2Fupdate-roxygen-docs.yml&type=code
https://github.com/search?q=nmfs-fish-tools%2Fghactions4r%2F.github%2Fworkflows%2Fstyle-description.yml&type=code
https://github.com/search?q=nmfs-fish-tools%2Fghactions4r%2F.github%2Fworkflows%2Fstyle-r-code.yml&type=code
