### ISSUE TITLE
[Feature]: Want a simple matrix of one OS

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nmfs-ost/ghactions4r#129]
### Is your feature request related to a problem? Please describe.

I want to run the R-CMD-Check GitHub action quickly every hour on just  one operating system.

### Describe the solution you would like.

I think it would be great if there were more options in [the github folder](https://github.com/nmfs-fish-tools/ghactions4r/tree/main/github) than just full and standard. But, this would lead to needing something other than an if else statement in the actions because there would be more than two options.

### Describe alternatives you have considered

* Write my own action and specify a single OS.
* Just run it on all three operating systems in the standard matrix.

### Additional context

I am willing to try and do a PR if you would like.

**Comment by k-doering-NOAA** [comment]
@kellijohnson-NOAA, it would be possible to implement this, but one question I have is if you think it is an option that would be useful to more than one project?

I'm realizing that workflows that aren't being run by a large number of projects can get out of date without users noticing (see #126) and am starting to think it may be best to only offer a curated selection of github actions here that are likely to get a lot of use.

I'm happy to review a PR, though, if you do feel it would be good to add to ghactions4r!

**Comment by kellijohnson-NOAA** [comment]
I understand the use vs. outdate problem. I think that most people are not going to want to run an action on just one operating system so I will close this issue and just use a custom workflow if it turns out that running it on 3 OSs is a computational burden. Thanks!
