### ISSUE TITLE
[Feature]: `allcontributors::add_contributors()`

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nmfs-ost/ghactions4r#143]
### Is your feature request related to a problem? Please describe.

I am thinking about adding contributor lists to the README of FIMS using `[allcontributors::add_contributors()](https://docs.ropensci.org/allcontributors/)` but it would be nice if this could be done using an automated workflow. I am happy to maintain this inside of FIMS if you think that there is not a desire to use this more widely. Below is a screen shot of what the NOAA-FIMS/FIMS README will look like once this is added.
![image](https://github.com/user-attachments/assets/11f815de-2e16-4b15-9ef5-75be2d68ee3e)

### Describe the solution you would like.

Have an GitHub action to source that creates a README with the below content
![image](https://github.com/user-attachments/assets/11f815de-2e16-4b15-9ef5-75be2d68ee3e)

### Describe alternatives you have considered

* Run it manually where it would be updated when remembered.
* Not add it to {ghactions4r} and instead have repositories copy the example below and place it in their repository.

### Additional context

Here is an [example GitHub action](https://github.com/ubvu/open-handbook/blob/e7a9fe6c730f72885e2c00c35136120159425149/.github/workflows/update-contributors.yml#L28) that creates a PR.

**Comment by k-doering-NOAA** [comment]
@kellijohnson-NOAA  that seems like a great way to feature contributors!

To me, this feels a little too specific to include in ghactions4r currently, so perhaps we could implement it in FIMS first? If it feels like it will be widely used by other packages, we can always move it here!

I'm closing for now, but feel free to reopen.
