### ISSUE TITLE
nmfs r users group lightning talks

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-ost/ghactions4r#19]
the NMFS R UG are doing lightning talks on May 10 - it might be nice for @Bai-Li-NOAA or me to do one to for ghactions4r to advertise the pkg better!

- [x] Prepare one slide to overview what is in ghactions4r and how to use these workflows
- [x] Generate dependents graphs to show which repositories are using workflows from ghactions4r (@Bai-Li-NOAA )

We are signed up! Guidelines:

Guidelines. Use 1 slide and 3 minutes to tell us about a tool/scientific document/report you and your team are working on! Below are 4 example slides to inspire you on your slide design, but feel free to do something different.
Add slides here:
https://docs.google.com/presentation/d/1HpmcCxFX_gj_L02jBfsOjVLWg8btA6Ym791XlxQjcFk/edit?usp=sharing
Need some inspiration? Here are the slides from the [November Lightning Talks](https://docs.google.com/presentation/d/1bG9vGR7WuQrz47mc3SnkZkCMSvShoPHrJS_6dOzxnqw/edit?usp=sharing)

**Comment by Bai-Li-NOAA** [comment]
Hi @k-doering-NOAA, I am trying to generate a dependents graph. However, I could not download the REST API data following the instructions [here](https://docs.github.com/en/rest/dependency-graph/dependency-review). I wonder if you could get any information after typing the commands below in a shell. 

```
curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/k-doering-NOAA/ghactions4r/dependency-graph/compare/BASEHEAD
```

```
curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/nmfs-fish-tools/ghactions4r/dependency-graph/compare/BASEHEAD
```

**Comment by k-doering-NOAA** [comment]
Hi Bai,

Powershell gives an error, but the git bash shell gives some info; however, this info is:

```
$ curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/nmfs-fish-tools/ghactions4r/dependency-graph/compare/BASEHEAD
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    84  100    84    0     0    564      0 --:--:-- --:--:-- --:--:--   567{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest"
}

```

**Comment by k-doering-NOAA** [comment]
Do you think BASEHEAD is supposed to be replaced with something?

**Comment by Bai-Li-NOAA** [comment]
I got same info that you have received. My guess is that we could provide the base and head Git revisions for the BASEHEAD. I will keep trying and keep you posted.

**Comment by Bai-Li-NOAA** [comment]
Hi @k-doering-NOAA, I have created a dependency-graph branch to work on the dependency graph in R. I am able to create a vignette and show the dependents of ghactions4r using the [DependenciesGraphs](https://github.com/datastorm-open/DependenciesGraphs) package. Since the graph is not a static figure, I need to create a vignette to show the interactive figure.

To check out the graph locally, you need to go to the dependency-graph branch, and use `pkgdown::build_site()` to preview the Dependency Graph vignette. Let me know if you have any suggestions. Below is the screenshot of the figure. 
![image](https://user-images.githubusercontent.com/59936250/165798644-7f82f31c-92d7-43e9-836d-cd271015fa16.png)

**Comment by k-doering-NOAA** [comment]
Very cool, thanks @Bai-Li-NOAA! I don't have any suggestions, I think it looks pretty good. If you want to add it to the main branch so that pkgdown can build it automatically and add it to the website, feel free!

**Comment by k-doering-NOAA** [comment]
Note users can see the [dependency graph](https://nmfs-fish-tools.github.io/ghactions4r/articles/dependency_graph.html) on the ghactions4r pkgdown site.

**Comment by k-doering-NOAA** [comment]
[Slide from the presentation](https://github.com/nmfs-fish-tools/ghactions4r/files/8927931/ghactions4r_R_UG_presentation.pdf)
