### ISSUE TITLE
workflow to detect/prevent hardcoded secrets in git repos

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [nmfs-ost/ghactions4r#23]
- Use [gitleaks](https://github.com/zricethezav/gitleaks) to detect and prevent hardcoded secrets (e.g., passwords, api keys, and tokens) in git repos
- It would be great if we could run gitleaks as a [pre-commit hook](https://pre-commit.com/) to identify issues before submitting commits

**Comment by k-doering-NOAA** [comment]
Thanks @Bai-Li-NOAA for including this suggestion! [The ghactions4r poll](https://github.com/nmfs-fish-tools/ghactions4r/issues/12#issuecomment-1095128005) indicated there was some interest in this (and I'm assuming some people may be interested and not realize it!)

**Comment by k-doering-NOAA** [comment]
see discussion on #48 as to why this is blocked.

**Comment by k-doering-NOAA** [comment]
There are now [secret scanning alerts for users](https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning#about-secret-scanning-alerts-for-users) that can be turned on in any public repository, so gitleaks seems less applicable. Unfortunately there is still no free solution for private repositories.
