### ISSUE TITLE
[Bug]: Warning in r cmd check about vignette not being built 

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-ost/ghactions4r#41]
### Describe the bug

A warning is seen during R CMD Check about not being able to build the vignettes, e.g., https://github.com/nmfs-fish-tools/ghactions4r/runs/6938085641?check_suite_focus=true#step:9:104

I thought it might be due to the `VignetteBuilder` in the `DESCRIPTION` file, but all the settings looked like vignettes in other packages. @Bai-Li-NOAA, do you have any ideas?

### To Reproduce

Run `devtools::check()` locally on the cloned main branch of `ghactions4r`

### Expected behavior

No warning about vignettes in R command check

**Comment by Bai-Li-NOAA** [comment]
Could be because I used ` %\VignetteEngine{rmarkdown::render}` in the Rmd file. Let me change it to `%\VignetteEngine{knitr::knitr}`, so it matches the VignetteBuilder in the DESCRIPTION.

**Comment by k-doering-NOAA** [comment]
I was wondering that! I can give this a try next week, if you haven't already tried it!

**Comment by Bai-Li-NOAA** [comment]
I created a branch to work on it and found other r-cmd-check notes that are related to the vignette. I am happy to continue working on it next week!

**Comment by k-doering-NOAA** [comment]
Thanks @Bai-Li-NOAA ! Sounds good!

**Comment by Bai-Li-NOAA** [comment]
change `%\VignetteEngine{rmarkdown::render}` to `%\VignetteEngine{knitr::rmarkdown}` and use visNetwork instead of DependenciesGraphs package fix the issue.
