### ISSUE TITLE
[Bug]:  update to use new environment files

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-ost/ghactions4r#54]
### Describe the bug

Current workflows use set-output, which will be deprecated in May 2023 and now produces a warning on action runs:
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment
 Files. For more information see: 
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

Instructions on how to fix here: 
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#examples

### To Reproduce

run a reusable workflow on from ghactions4r and look at the annotations

### Expected behavior

no warning produced

**Comment by kellijohnson-NOAA** [comment]
@k-doering-NOAA I found [a blog post on dev.to/cicirello](https://dev.to/cicirello/how-to-patch-the-deprecated-set-output-in-github-workflows-and-in-container-actions-9co) helpful for reconfiguring set-output.

**Comment by k-doering-NOAA** [comment]
The r-cmd-check job is not working with the new environmental files. I think the issue is that this workflow passes on an output from a previous job in the workflow to the next job in the workflow. I suspect it is the `runs-on:` specification that is causing the problem. I tried to look up examples, but the solutions seem to be what I am doing, so I am not sure how to fix this currently.

**Comment by k-doering-NOAA** [comment]
Luckily, was able to get help here: https://github.com/community/community/discussions/42790

Sorry if any users of the workflow saw downtime the last hour or 2 when I thought I had fixed the issue, but merged in a buggy workflow. r-cmd-check should now be working again.
