### ISSUE TITLE
[Bug]: peter-evans/create-pull-request@v3 should be updated to v4

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nmfs-ost/ghactions4r#56]
### Describe the bug

peter-evans/create-pull-request@v3 should be updated to v4 according to the [README](https://github.com/peter-evans/create-pull-request/blob/ee93d78b55ada32aa74b5e9957aac9c2523dd22c/README.md?plain=1#L34) on [peter-evans/create-pull-request](https://github.com/peter-evans/create-pull-request).

This affects the following lines of code in this repository:
https://github.com/nmfs-fish-tools/ghactions4r/blob/ba096637ce4b5cdb90332d0e46b67a55217e687d/.github/workflows/update-roxygen-docs.yml#L43
https://github.com/nmfs-fish-tools/ghactions4r/blob/ba096637ce4b5cdb90332d0e46b67a55217e687d/.github/workflows/style-r-code.yml#L44
https://github.com/nmfs-fish-tools/ghactions4r/blob/ba096637ce4b5cdb90332d0e46b67a55217e687d/.github/workflows/doc-and-style-r.yml#L128

### To Reproduce

When the GitHub actions are ran the following error message is generated in GitHub actions
```
Node.js 12 actions are deprecated.
For more information see:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the following actions to use Node.js 16: peter-evans/create-pull-request@v3
```

### Expected behavior

No warnings from the GitHub action. Once the actions are updated to use v4 the warning regarding the node goes away. I have tested this in a different repository.

### Additional Context

I will submit a pull request for this.

**Comment by k-doering-NOAA** [comment]
Thanks for catching this @kellijohnson-NOAA and offering to submit a PR! That would be great.
