### ISSUE TITLE
installation of dependencies in doc-and-style causing problems?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-ost/ghactions4r#69]
Hi @k-doering-NOAA,
Thanks for the continued usefulness of {ghactions4r} and sorry to bug you with a problem.

A recent change in r4ss to use `importFrom` of specific functions within {kableExtra} rather than the whole package (which caused a conflict with dplyr, see https://github.com/r4ss/r4ss/pull/819). 

Now, the call-doc-and-style workflow [is failing](https://github.com/r4ss/r4ss/actions/runs/5137774039/jobs/9269899952#step:10:12) with the error `Error: Error in load_imports(path) : The package "kableExtra" is required.` Looking back through the action messages, I see (at [this point](https://github.com/r4ss/r4ss/actions/runs/5137774039/jobs/9269899952#step:7:12892)):
```
ERROR: dependency ‘rvest’ is not available for package ‘kableExtra’
* removing ‘/home/runner/work/_temp/Library/kableExtra’
```

This is not an error in other packages or locally on my machine. 
@kellijohnson-NOAA wisely pointed out that the dependency installation might be different in doc-and-style than in other actions, and indeed, I see the use of `remotes::install_deps(dependencies = TRUE)` at https://github.com/nmfs-fish-tools/ghactions4r/blob/eb8b6fb50fbc533efe861b56b010ee2fe716a408/.github/workflows/doc-and-style-r.yml#L50
as opposed to the `r-lib/actions/setup-r-dependencies` used in doc-and-style prior to https://github.com/nmfs-fish-tools/ghactions4r/commit/eb8b6fb50fbc533efe861b56b010ee2fe716a408 as well as in other yml files. I don't know the history that prompted the change, but before that commit, doc-and-style was using `setup-r-dependencies@v1` whereas others are using `v2` (e.g. [r-cmd-check](https://github.com/nmfs-fish-tools/ghactions4r/blob/d2fbfe704bc3e9666b176d091eeed984596c5302/.github/workflows/r-cmd-check.yml#L71)). Would it be worth trying ``setup-r-dependencies@v2` to see if that works for whatever cases necessitated the change as well as fixing the r4ss action?

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA thanks so much! I think I missed this one when I updated all the other workflows to use `setup-r-dependencies@v2` and replacing it (already merged in) seems to work- I just ran doc and style on the r4ss main branch manually and it worked fine, generating https://github.com/r4ss/r4ss/pull/821

Feel free to reopen if problems pop up.

**Comment by iantaylor-NOAA** [comment]
Looks good. Thank you for dealing with this!
