### ISSUE TITLE
[Bug]: curl dependency 404 Not Found error - call-doc-and-style-r workflow

### ISSUE THREAD

**Issue by efletcherPIFSC** [nmfs-ost/ghactions4r#90]
### Describe the bug

Getting errors with call-doc-and-stlyle-r workflow github action, and traced the error downloading the `libcurl4-openssl-dev` library dependency (see logfile line 475-490).

This issue is may be similar to what is discussed at https://github.com/actions/runner-images/issues/6486

### To Reproduce

Attempted failed jobs on https://github.com/PIFSCstockassessments/ss3diags/actions/runs/5616600564

### Expected behavior

call-doc-and-style-r previously downloaded `libcurl4-openssl-dev` without issue

### Screenshots

Logfile:
[1_call-workflow  doc and style.txt](https://github.com/nmfs-fish-tools/ghactions4r/files/12131651/1_call-workflow.doc.and.style.txt)

### Which version of ghactions4r are you seeing the problem on?

doc-and-style-r.yml@main

**Comment by k-doering-NOAA** [comment]
@efletcherPIFSC thanks for reporting! How long has this been occurring? Sometimes dependencies fail to download but rerunning a short time later solves the issue...

If it isn't fixed by Monday, please let me know and I can see if there is something to do in the workflow itself. Thanks for reporting!

**Comment by iantaylor-NOAA** [comment]
I ran into this as well. Looking at discussions like https://stackoverflow.com/questions/74249584/why-did-github-ci-just-start-failing-to-locate-libcurl made me hope that it would just go away soon, but it's been more than 24 hours so maybe it's something deeper.

@k-doering-NOAA, why was the curl dependency needed in d6292e4b91a05011af2f523c056cf1bf474205f3? 

And could adding `sudo apt-get update` be the solution as discussed in: https://github.com/actions/runner-images/issues/5470?

**Comment by k-doering-NOAA** [comment]
Thanks @iantaylor-NOAA , although sorry to hear it is failing for you, also. @kellijohnson-NOAA figured out it was needed to run `usethis::use_tidy_description()`, which is now part of the doc and style workflow. 

Good point about apt-get update, I will look into that Monday if this is a persistant issue!

**Comment by iantaylor-NOAA** [comment]
@k-doering-NOAA 
Sounds good, thanks for the quick response. We'll check in on this next week.

**Comment by efletcherPIFSC** [comment]
@k-doering-NOAA The 404 Error began yesterday (7/20), re-ran it again today to check if it went away, and it also failed to run when I asked Megumi to re-ran the failed job.

**Comment by iantaylor-NOAA** [comment]
@efletcherPIFSC, note that you can run all of the commands locally to work around the non-working GitHub Action while waiting for a fix.
```
usethis::use_tidy_description()
devtools::document() 
styler::style_pkg()
```

The `rm_dollar_sign()` step requires a few lines of code here:
https://github.com/nmfs-fish-tools/ghactions4r/blob/main/.github/workflows/doc-and-style-r.yml#L88-L93

I should also note that by hoping that "it would just go away soon" I mean that hopefully the hardworking folks who work for GitHub and Microsoft and Ubuntu will resolve whatever issue is causing the unavailability of libcurl on the servers.

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA and @efletcherPIFSC , I just pushed apt-get update to main, let me know if that works or not (feel free to reopen this issue if still running into problems)

**Comment by kellijohnson-NOAA** [comment]
Sorry everyone for introducing this error in the first place 🤦. For a bit of background, I found that when a package that you are installing uses {curl}, then you need to install libcurl prior to installing the R package curl. There is some guidance [on stack exchange](https://stackoverflow.com/questions/31686470/install-curl-and-readr-on-r) from 2015 and [on omegahat.net](https://www.omegahat.net/RCurl/FAQ.html). Obviously, I didn't do this in the best way. Thanks to @iantaylor-NOAA and @k-doering-NOAA for 🧹 up my mess.

**Comment by k-doering-NOAA** [comment]
@kellijohnson-NOAA it was an easy fix! No sweat. Thanks for adding the description styling :)

**Comment by efletcherPIFSC** [comment]
@k-doering-NOAA Changes worked, no curl dependency errors.  Note that I selected "Re-run failed jobs" first, with the same error, then I selected  "Re-run All Jobs" which worked.

**Comment by k-doering-NOAA** [comment]
> @k-doering-NOAA Changes worked, no curl dependency errors. Note that I selected "Re-run failed jobs" first, with the same error, then I selected "Re-run All Jobs" which worked.

Ah, thanks for the heads up!
